
version: "3"

services:
#  mysql:
#    image: mysql:8.0
#    volumes:
#      - /tmp:/tmp
#    networks:
#      - network
#    ports:
#      - 3306
#    environment:
#      MYSQL_HOST: "localhost"
#      MYSQL_USER: "admin"
#      MYSQL_PASSWORD: "cmpe172"
#    restart: always
  starbucks:
    image: abahror/spring-starbucks-api:3.1
    volumes:
      - /tmp:/tmp
    networks:
      - network   
    ports:
      - 8080    
    environment:
      MYSQL_HOST: "35.222.164.252"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "cmpe172"
    restart: always     
  lb:
    image: eeacms/haproxy
    depends_on:
    - starbucks
    ports:
    - "80:5000"
    - "1936:1936"
    environment:
      BACKENDS: "starbucks"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "false"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

