apiVersion: v1
kind: Service
metadata:
  name: cashier-web-app-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    name: cashier-web-app